title: Gitnamu
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: ""
url: "https://gitnamu.github.io"


author:
  name: 'Kim Namho'
  last_name: 'Kapitonenko'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  gitnamu
  email: vika@kaptn.ru
  vk_id: id201664979
  telegram_name: vikapitoshka
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html
